# Generated by Django 3.0.7 on 2021-04-27 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hack.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.TextField(default='')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(max_length=50)),
                ('M1_Name', models.CharField(max_length=100)),
                ('M1_email', models.EmailField(max_length=254, null=True)),
                ('M1_Mobile_no', models.CharField(max_length=10, null=True)),
                ('M1_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('M2_Name', models.CharField(max_length=100)),
                ('M2_email', models.EmailField(max_length=254, null=True)),
                ('M2_Mobile_no', models.CharField(max_length=10, null=True)),
                ('M2_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('M3_Name', models.CharField(max_length=100)),
                ('M3_email', models.EmailField(max_length=254, null=True)),
                ('M3_Mobile_no', models.CharField(max_length=10, null=True)),
                ('M3_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('M4_Name', models.CharField(blank=True, max_length=100)),
                ('M4_email', models.EmailField(blank=True, max_length=254)),
                ('M4_Mobile_no', models.CharField(blank=True, max_length=10)),
                ('M4_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('M5_Name', models.CharField(blank=True, max_length=100)),
                ('M5_email', models.EmailField(blank=True, max_length=254)),
                ('M5_Mobile_no', models.CharField(blank=True, max_length=10)),
                ('M5_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('Mentor_Name', models.CharField(default=' ', max_length=100)),
                ('Mentor_email', models.EmailField(default=' ', max_length=254, null=True)),
                ('Mentor_Mobile_no', models.CharField(default=' ', max_length=10, null=True)),
                ('Mentor_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=' ', max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.FileField(blank=True, default='', upload_to=hack.models.user_directory_path)),
                ('problem_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hack.problem')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
